name: Docker Image Published to AWS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to AWS ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Pull image from Docker Hub
      run: |
        docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/imagename

    - name: Tag Docker image for AWS ECR
      run: |
        docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/imagename 219175043466.dkr.ecr.us-east-1.amazonaws.com/imagename

    - name: Push image to AWS ECR
      run: |
        docker push 219175043466.dkr.ecr.us-east-1.amazonaws.com/imagename

    - name: Create new task definition
      run: |
        aws ecs register-task-definition \
        --family your-task-family \
        --execution-role-arn arn:aws:iam::219175043466:role/your-ecs-task-execution-role \
        --container-definitions "$(cat task-definition.json)"