name: Docker Image Tested

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: node.js setup
      uses: actions/setup-node@v2
      with: 
        node-version: '18.x'

    - name: Build the Docker image
      run: docker build . --file Dockerfile -t imagename

    - name: Run Docker container
      run: docker run -d -p 80:80 imagename

    - name: run tests
      uses: liatrio/github-actions/apprentice-action@master
