name: Docker Image Compiled, Tested, & Deployed

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      
      #Verify the application functionality using Liatrio’s GitHub apprentice-action
      #https://github.com/liatrio/github-actions/tree/master/apprentice-action
      #Pushes image to Docker Hub
